### ISSUE TITLE
[doc] Issue in "SSL for RGW in 7.1" - got an unexpected keyword argument 'rgw_frontend_ssl_key'

### ISSUE THREAD

**Issue by Martin-Weiss** [SUSE/doc-ses#1031]
### Type of report
   - [ x] bug
   - [ ] feature request

### Source Document[
https://documentation.suse.com/ses/7.1/single-html/ses-deployment/#cephadm-deploy-using-secure-ssl-access

### Summary
the rgw_frontend_ssl_key does NOT exist in 7.1 / pacific anymore!

### Steps To Reproduce
Follow the docs and apply rgw.yaml - you will get the above error

### Expected Results
Deployment works without a problem

### Actual Results
Fails

### Notes
Seems the admin and deployment guides need to cover the changed for pacific!

**Comment by trociny** [comment]
A quick research shows that is was removed in this PR [1], more exactly this commit [2], and the idea is that instead of two params rgw_frontend_ssl_certificate and rgw_frontend_ssl_key we have now only one rgw_frontend_ssl_certificate, where both the certificate and the key should be concatenated as one value. We may want the cephadm team to confirm.

[1] https://github.com/ceph/ceph/pull/42305
[2] https://github.com/ceph/ceph/commit/4fe35117ce2349adc023604ead1c37c8680b90c4

**Comment by mgfritch** [comment]
yes, both certificate and key should be concatenated into the `rgw_frontend_ssl_certificate`[1].

[1] https://docs.ceph.com/en/pacific/cephadm/services/rgw/#setting-up-https

**Comment by tbazant** [comment]
> rgw_frontend_ssl_key

@trociny can you please review this one https://github.com/SUSE/doc-ses/pull/1032/files ?
