### ISSUE TITLE
SES6 Administration Guide: strange lettering of Appendixes

### ISSUE THREAD

**Issue by smithfarm** [SUSE/doc-ses#312]
**Link To Section**

SES6 Administration Guide, Table of Contents

**Summary**

The appendices are numbered strangely.

**Steps To Reproduce**

Examine the ToC, see the following:

```
A DeepSea Stage 1 Custom Example
B Ceph Maintenance Updates Based on Upstream 'Nautilus' Point Releases
Glossary
C Documentation Updates

    C.1 Maintenance update of SUSE Enterprise Storage 6 documentation
    C.2 June 2019 (Release of SUSE Enterprise Storage 6)
```

and note that the appendix "Glossary" (with no letter) is situated after Appendix B, and before Appendix C.

**Expected Results**

My expectation would be that the Appendices would have ascending letters, with no skipped letters. Also, if there are both lettered and unlettered appendices, the lettered ones would come first, and the unlettered ones second, instead of the unlettered ones being interspersed among the lettered ones.

**Comment by asettle** [comment]
So, context, this is because the Glossary within XML is a specific syntax, which you can see here: https://github.com/SUSE/doc-ses/blob/master/xml/ses_glossary.xml#L8 vs. the appendix, which uses something different: https://github.com/SUSE/doc-ses/blob/master/xml/tuning-appendix.xml#L7

What we did in the Tuning Guide was re-arrange the Glossary so that it was the last option, and didn't interrupt the flow, what do you think? https://susedoc.github.io/doc-ses/ses6/single-html/ses-tuning/
