### ISSUE TITLE
[doc] 14.9  Testing Network Performance

### ISSUE THREAD

**Issue by asettle** [SUSE/doc-ses#536]
### Type of report
   - [x] bug
   - [ ] feature request

### Source Document
14.9  Testing Network Performance:

https://susedoc.github.io/doc-ses/master/html/ses-troubleshooting/storage-tips.html#storage-bp-network-test

### Summary
Section needs to be complete now that the net runner has been merged. 

### Notes
Also need to update: https://susedoc.github.io/doc-ses/master/html/ses-troubleshooting/storage-tips.html#storage-bp-performance-net-issues (see the NOTE in the dot point series)

**Comment by swiftgist** [comment]
Intermittent and complete network failures will impact a Ceph cluster. These two utilities can help in tracking down the cause and verifying expectations.

### Basic diagnostics 
Try the runner `network.ping` to ping between cluster nodes to see if individual interface can reach to specific interface and the average response time. Any specific response time much slower then average will also be reported. For example:

```
root@master # salt-run network.ping
  Succeeded: 8 addresses from 7 minions average rtt 0.15 ms
```
or for IPv6:
```
root@master # salt-run network.ping6
  Succeeded: 8 addresses from 7 minions average rtt 0.15 ms
```

Try validating all interfaces with JumboFrame enabled:
```
root@master # salt-run network.jumbo_ping
  Succeeded: 8 addresses from 7 minions average rtt 0.26 ms
```

### Throughput benchmark 
Try the runner `network.iperf` to test network bandwidth between each pair of interfaces. On a given cluster node, a number of iperf processes (according to the number of CPU cores) are started as servers. The remaining cluster nodes will be used as clients to generate network traffic. The accumulated bandwidth of all per-node iperf processes is reported. This should reflect the maximum achievable network throughput on all cluster nodes. For example:

```
root@master # salt-run network.iperf 
Fastest 2 hosts:
    |_
      - 192.168.31.25
      - 11443 Mbits/sec
    |_
      - 172.16.31.25
      - 10363 Mbits/sec

Slowest 2 hosts:
    |_
      - 172.16.32.14
      - 10217 Mbits/sec
    |_
      - 192.168.121.164
      - 10113 Mbits/sec
```
### Useful options

The `output=full` option will list the results of each interface rather than the summary of the two slowest and fastest.
```
root@master # salt-run network.iperf output=full
192.168.128.1:
    8644.0 Mbits/sec
192.168.128.2:
    10360.0 Mbits/sec
192.168.128.3:
    9336.0 Mbits/sec
192.168.128.4:
    9588.56 Mbits/sec
192.168.128.5:
    10187.0 Mbits/sec
192.168.128.6:
    10465.0 Mbits/sec
```

The `remove=network` where network is a comma delimited list of subnets that should not be included.
```
root@master # salt-run network.ping remove="192.168.121.0/24,192.168.1.0/24"
Succeeded: 20 addresses from 10 minions average rtt 14.16 ms
```

**Comment by swiftgist** [comment]
Let me know your thoughts.  I believe the above can replace the entire section up to the last two points about the firewall and network hardware notes.

**Comment by asettle** [comment]
@swiftgist it looks good! Thanks for writing this up. Are you comfortable with doing the PR change yourself? :)
