### ISSUE TITLE
Review and update CIFS chapter in SES7 Admin guide

### ISSUE THREAD

**Issue by tbazant** [SUSE/doc-ses#586]
**Link To Section**
https://susedoc.github.io/doc-ses/master/html/ses-admin/cha-ses-cifs.html

**Summary**
Please review CIFS chapter so that it is correct for SES 7

**Notes**
Pay extra attention to occurences of `ceph.conf` as now SES uses configuration DB

**Comment by ddiss** [comment]
Alex and I discussed this again today. At this point I'm comfortable that the SES7 documentation is correct as-is. The main reason being that we've always required manual deployment of Samba/CTDB services, rather than going via Deepsea / Orchestrator.
I'll keep this ticket open until I've finished testing, but I don't expect anything significant to come up.

**Comment by asettle** [comment]
@ddiss any update on testing? :) Thanks for reviewing!

**Comment by asettle** [comment]
Leaving this doc bug open for results on: https://bugzilla.suse.com/show_bug.cgi?id=1177245

**Comment by ddiss** [comment]
1177245 has been closed. closing here too.
