### ISSUE TITLE
Ensure point releases from upstream are documented for SES 7

### ISSUE THREAD

**Issue by asettle** [SUSE/doc-ses#605]
Point releases require doucmentation before Oct 19: https://susedoc.github.io/doc-ses/master/single-html/ses-deployment/#id-1.3.6

**Comment by smithfarm** [comment]
### 15.2.1

The Octopus point release 15.2.1 fixed an issue where upgrading quickly from Luminous (SES5.5) to Nautilus (SES6) to Octopus (SES7) caused OSDs to crash. In addition, it patched two security vulnerabilities that were present in the initial Octopus (15.2.0) release:

* CVE-2020-1759: Fixed nonce reuse in msgr V2 secure mode
* CVE-2020-1760: Fixed XSS due to RGW GetObject header-splitting

### 15.2.2

The Octopus point release 15.2.2 patched one security vulnerability:

* CVE-2020-10736: Fixed an authorization bypass in MONs and MGRs

### 15.2.3

The Octopus point release 15.2.3 was a hotfix release to address an issue where WAL corruption was seen when `bluefs_preextend_wal_files` and `bluefs_buffered_io` were enabled at the same time. The fix in 15.2.3 is only a temporary measure (changing the default value of `bluefs_preextend_wal_files` to "false"). The permanent fix will be to remove the `bluefs_preextend_wal_files` option completely: this fix will most likely arrive in the 15.2.6 point release.

### 15.2.4

The Octopus point release 15.2.4 brought the following fixes and other changes:

* CVE-2020-10753: rgw: sanitize newlines in s3 CORSConfiguration’s ExposeHeader
* RGW: The radosgw-admin sub-commands dealing with orphans – `radosgw-admin orphans find`, `radosgw-admin orphans finish`, and `radosgw-admin orphans list-jobs` – have been deprecated. They had not been actively maintained, and since they store intermediate results on the cluster, they could potentially fill a nearly-full cluster. They have been replaced by a tool, `rgw-orphan-list`, which is currently considered experimental.
* RBD: The name of the rbd pool object that is used to store rbd trash purge schedule is changed from `rbd_trash_trash_purge_schedule` to `rbd_trash_purge_schedule`. Users that have already started using rbd trash purge schedule functionality and have per pool or namespace schedules configured should copy the `rbd_trash_trash_purge_schedule` object to `rbd_trash_purge_schedule` before the upgrade and remove `rbd_trash_purge_schedule` using the following commands in every RBD pool and namespace where a trash purge schedule was previously configured:

    rados -p <pool-name> [-N namespace] cp rbd_trash_trash_purge_schedule rbd_trash_purge_schedule
    rados -p <pool-name> [-N namespace] rm rbd_trash_trash_purge_schedule

or use any other convenient way to restore the schedule after the upgrade.

### 15.2.5

The Octopus point release 15.2.5 brought the following fixes and other changes:

* CephFS: Automatic static subtree partitioning policies may now be configured using the new distributed and random ephemeral pinning extended attributes on directories. See the following documentation for more information: https://docs.ceph.com/docs/master/cephfs/multimds/
* Monitors now have a config option `mon_osd_warn_num_repaired`, which is set to 10 by default. If any OSD has repaired more than this many I/O errors in stored data a `OSD_TOO_MANY_REPAIRS` health warning is generated.
* Now, when `no scrub` and/or `no deep-scrub` flags are set globally or per pool, scheduled scrubs of the type disabled will be aborted. All user initiated scrubs are NOT interrupted.
* Fixed an issue with osdmaps not being trimmed in a healthy cluster.

**Comment by smithfarm** [comment]
@asettle Is this enough, or is more needed from my side?

**Comment by asettle** [comment]
> @asettle Is this enough, or is more needed from my side?

Perfect, thanks :smile:
