### ISSUE TITLE
[doc] 15.4  Create an NFS Export

### ISSUE THREAD

**Issue by supriti** [SUSE/doc-ses#765]
https://documentation.suse.com/ses/7/single-html/ses-admin/#ceph-nfsganesha-create-export

We can expand it and explain with an example on how each of the three config files should look like: bootstrap-config, common-config and export-config (Similar to confluence doc created by @mgfritch). Without using dashboard, deploying nfs-ganesha would require end user to modify lot of config files by hand. An example would make it easier to follow. 

As we will be providing only a basic export file example, we should ask users to refer to man pages for more options.

**Comment by tbazant** [comment]
@supriti @mgfritch to expand that section, i need the input + example. maybe it already exists in confluence, the attach the link here please

**Comment by supriti** [comment]
This is the page I am referring to :https://confluence.suse.com/display/SUSEEnterpriseStorage/nfs-ganesha

**Comment by asettle** [comment]
Hmm @supriti so I've been thinking about this for a little while. The only reason I chose not to include this the first time around was because this is a administration guide, and if we provided every configuration reference point, well, we'd have a configuration reference guide. Is this content available upstream? Or, can we do as you said and point the user directly to the man pages.

**Comment by asettle** [comment]
@mgfritch @tbazant - what do you think about including these files? Is it worth it (now)?
