### ISSUE TITLE
SES7: 1  Available Documentation hyperlinks are reversed

### ISSUE THREAD

**Issue by smithfarm** [SUSE/doc-ses#769]
### Type of report
   - [x] bug
   - [ ] feature request

### Source Document
1  Available Documentation:

https://documentation.suse.com/ses/7/single-html/ses-deployment/#id-1.3.2.7

### Summary

This section presents a list of documentation resources (books): 

* Deployment Guide
* Book “Operations and Administration Guide”
* Book “Security Hardening Guide”
* Book “Troubleshooting Guide”
* Book “SUSE Enterprise Storage for Windows Guide”

The first item of the list is the Deployment Guide itself (the very book we are reading). This one is a hyperlink, and the remaining ones (Book "X", Book "Y", etc.) are not hyperlinks.

It should be the opposite. The reader does not need a hyperlink to the very book they are reading. They need hyperlinks to the *other* books.

**Comment by asettle** [comment]
Yes, that's correct. Our styling supports cross-referencing between guides, but you'll note that throughout the guides you won't find hyperlinks, they'll be detailed reference points instead.

@sknorr @tomschr anything we can do about this? :)

**Comment by tomschr** [comment]
@asettle This is currently a problem and hard to change.

Currently, the SES Guide is built from a set and it contains different books. So if you have a valid XML file, all ID/IDREFs are correct.

However, if you render a single book from your set you might have a problem. You need to distinguish between two cases:

* "Inside references"
  These are references which stays inside the book. For example, if you have a reference from chapter 1 to chapter 2 of the same book, that will work.
  The reference will appear as a clickable text, both in HTML and PDF.

* "Outside references"
  These are references that go **outside** of your current book. For example, if you references from Deployment Guide into the Administration Guide.

  The stylesheets can extract the text of the target title. However, they cannot create a link. In case of HTML, the HTML page wouldn't be rendered at all (because the build process renders only one book). For PDF, such a reference cannot be created at all.

That's why you see a working references to the Deployment Guide, but no clickable text for the other guides. All your references would work if you build the complete set (try it!).

I currently see only these solutions:

* Remove the specific references and turn them into a link. Let them point to the SUSE documentation page, pointing to SES in general.
  Unfortunately, this could bring other issues
* Ignore, live with this problem. :wink:

I'm sorry, I cannot give you a better solution. That's the current situation.

**Comment by asettle** [comment]
Thanks for the thorough review, @tomschr - sounds about right. What problems do you foresee with linking them directly to d.s.c? Potential redirects or something else?

**Comment by tomschr** [comment]
Well, directly linking them to d.s.c would work if the pages are there. :wink:  If you have a prerelease that isn't published on d.s.c, then you might have a problem. Although, it's a small one.

**Comment by asettle** [comment]
That's okay though, to solve this as an immediate issue: that will work just fine. But we need to make sure for future releases we update the link according to the URL structure. Thanks for your help :)

**Comment by tomschr** [comment]
You could use `&productnumber;` in your link:

```
<link xlink:href="https://documentation.suse.com/ses/&productnumber;/...">...</link>
```

Technically, it would work and you don't need to think about this link. You only need to make sure, you update the entity. :wink:

**Comment by asettle** [comment]
Good shout! Thanks!

**Comment by tomschr** [comment]
I forgot to tell you, I think the URL works also _without_ a product version. It will then call the latest version.

Not entirely sure if this would be a good or bad think. :thinking:

**Comment by asettle** [comment]
@tomschr hmm, that would be the best solution. Indeed if you click on https://documentation.suse.com/ses/single-html/ses-admin/#book-storage-admin it automatically sets you to the latest version. That would make life a million times easier for this exact instance.

**Comment by tomschr** [comment]
Another idea you can think of: you could introduce an entity as a root URL. For example:

```
<!ENTITY sesroot "https://documentation.suse.com/ses/single-html/">
```

which can be used like this:

```
<link xlink:href="&sesroot;/#book-storage-admin">...</link>
```

Would create the same link. Benefits:

* URLs are way shorter and easier to handle
* Maintenance is a bit easier
* If you want to change the URL, change the entity :tada: 

Drawbacks:

* Grep wouldn't work anymore (but you can grep for `sesroot`)
* Maybe your cat doesn't like it?

**Comment by sknorr** [comment]
Be aware that this change will lead to less useful links in what is supposed to be the main version of our documentation (the multi-page HTML), that currently has working links to all the guides... cf. https://documentation.suse.com/ses/7/html/ses-all/bk01pr01.html#id-1.3.2.7

**Comment by asettle** [comment]
Do you have another suggestion, @sknorr? :)

**Comment by sknorr** [comment]
Options:

1. Keep the current thing, so it at least works for normal HTML (though not for the other versions)
2. Use the new version but link to normal HTML instead of single HTML.
3. Use both and profile differently between single HTML/PDF/EPUB and normal HTML. (However, that will have the negative side effect of affecting display on the nav page at doc.suse.com/ses/7, so I would not recommend it.)

The long-term solution is something like this, https://confluence.suse.com/x/3wBqH but that is not yet implemented.

**Comment by asettle** [comment]
> Options:
> 
> 1. Keep the current thing, so it at least works for normal HTML (though not for the other versions)

I'd say we need this to work for both versions.

> 2. Use the new version but link to normal HTML instead of single HTML.

This is already the case.

> 3. Use both and profile differently between single HTML/PDF/EPUB and normal HTML. (However, that will have the negative side effect of affecting display on the nav page at doc.suse.com/ses/7, so I would not recommend it.)

How does this work? But if you don't recommend it, let's just not consider it. I'd rather go with what is possible, simple, and supportable.

> 
> The long-term solution is something like this, https://confluence.suse.com/x/3wBqH but that is not yet implemented.

Ah, yes. That would be good. Do we have a date for this?

**Comment by sknorr** [comment]
>This is already the case.

Ah, I missed that part, sorry.


> Ah, yes. That would be good. Do we have a date for this?

Nope.
