### ISSUE TITLE
Improve SES 6 upgrade documentation

### ISSUE THREAD

**Issue by asettle** [SUSE/doc-ses#843]
**Link To Section**

https://documentation.suse.com/ses/6/single-html/ses-deployment/#cha-ceph-upgrade

**Summary**

A large number of customers will be upgrading from 5 -> 6 with the EOL happening in January. We need to clean up the docs to make this a more linear process with clear guidelines.

**Basic Example**

Nathan outlined basic steps to take:

1. structure the upgrade chapter as a series of steps
2. at the beginning of the chapter, explain that there are two methods of upgrading: DMS and ISO, what they are, what the difference between them is
3. label each step in the procedure so it's clear that the step applies to the "ISO method", "DMS method", or "both methods"

**Motivation**

It's not great.

**Notes**

See: https://github.com/SUSE/doc-ses/pull/842

**Comment by tbazant** [comment]
@smithfarm, my comments follow:
> 
>     1. structure the upgrade chapter as a series of steps
If you look at the attached picture, it makes a series of steps
see ![obrazek](https://user-images.githubusercontent.com/2240174/103660148-8ff28f80-4f6d-11eb-94e5-3c08f82180d4.png)

> 
>     2. at the beginning of the chapter, explain that there are two methods of upgrading: DMS and ISO, what they are, what the difference between them is
These 2 methods are described just before the actual nodes' upgrades ->  https://documentation.suse.com/ses/6/single-html/ses-deployment/#upgrade-one-node
Shall I move it to some other place?
> 
>     3. label each step in the procedure so it's clear that the step applies to the "ISO method", "DMS method", or "both methods"

**Comment by smithfarm** [comment]
@tbazant Strictly speaking, those section headings do not make a series of steps. Some of them are steps, others are explanations. At least, the following sections do not appear to be steps to me:

* Points to consider before the upgrade (explanation, not step)
* Per Node Upgrade - Basic Procedure (this appears to be a series of steps, not a single step, and it's not clear where it fits in the order of steps)
* Final Steps (not a step)

The other sections are titled in imperative mood ("do this", "do that"). But these three are not. This creates cognitive dissonance and makes the reader work harder than necessary IMO.

Therefore, my suggestions are as follows:

1. break "Points to consider before the upgrade" into a series of steps. Make each step a separate section. Name each step using the imperative mood. For example: "Ensure that all nodes are fully patched".
2. similarly, break "Final steps" into a series of steps. Make each step a separate section. Name each step using the imperative mood.
3. "Per node upgrade - basic procedure" is really problematic because it applies to multiple steps. That's why I suggested to restructure the chapter. One way the structure could be is as follows:

Upgrading From Previous Releases
* Introduction
* Steps to take before upgrading the first node
* Order in which nodes must be upgraded
* Per-node upgrade instructions
* Steps to take after the last node has been upgraded

**Comment by tbazant** [comment]
@smithfarm i'm halfway thru, attaching the new structure
![obrazek](https://user-images.githubusercontent.com/2240174/103767397-d1904280-5020-11eb-862b-41cc51703324.png)
and also rendered the current version
[cha-ceph-upgrade_color_en.pdf](https://github.com/SUSE/doc-ses/files/5775680/cha-ceph-upgrade_color_en.pdf)

Please, suggest further changes / reshuffling of sections

**Comment by smithfarm** [comment]
OK... some more things to consider:

1. I noticed that the new text is using a confusing (for me) term "application nodes". Are we really using that term instead of "gateway nodes"? (I think "gateway nodes" is clearer, since these are nodes that run gateways, not nodes that run applications, so I suggest to change "application nodes" to "gateway nodes" here and everywhere else in the documentation.)

2. The chapter "Steps to Take after the Last Node Has Been Upgraded" should be really after the last node. Right now, from the ordering of the sections it seems like these steps should be taken after OSD nodes have been upgraded, but before the gateway nodes have been upgraded. Therefore, I believe the section should be moved to the very end, after the gateway nodes. Why? Because the chapter starts with the following sentence: "For each host that has been upgraded — OSD, MON, MGR, MDS, **and Gateway nodes**, as well as client hosts — update your ceph.conf file..."

**Comment by smithfarm** [comment]
Also, typo:

6.2.7 Consolidate Srub-related Configuration

(should be "Scrub-related")

**Comment by smithfarm** [comment]
One more thing (very important!)

6.11 OSD Migration to BlueStore

OSD migration to BlueStore must be completed while the cluster is still on SES5 - i.e., it is a **prerequisite** for upgrading, and should definitely be moved into "6.2 Steps to Take before Upgrading the First Node". Also, I think the documentation should emphasize more that the upgrade should not be attempted if there are any FileStore OSDs in the cluster (since FileStore OSDs are unsupported in SES6, upgrading the cluster to SES6 in this state will result in an unsupported cluster configuration!).

**Comment by tbazant** [comment]
@smithfarm your suggestions are addressed, see 
[cha-ceph-upgrade_color_en.pdf](https://github.com/SUSE/doc-ses/files/5795064/cha-ceph-upgrade_color_en.pdf)

**Comment by tbazant** [comment]
closed in https://github.com/SUSE/doc-ses/pull/878
