### ISSUE TITLE
Return post-upgrade cleanup section

### ISSUE THREAD

**Issue by tbazant** [SUSE/doc-ses#853]
```
<sect1 xml:id="upgrade-post-cleanup">
  <title>Post-upgrade Clean-up</title>
<screen>
  # ceph versions
  # ceph osd require-osd-release octopus
  # ceph mgr module enable pg_autoscaler
  # ceph mgr module enable telemetry
  # ceph telemetry on
  # ceph osd set require-min-compat-client luminous
  # ceph balancer mode upmap
  # ceph balancer on
  [...]
</screen>
 </sect1>
```

with the following description:

- To verify that the cluster was sucessfully upgrade, `run ceph versions` and verify the ceph version
- `ceph osd require-osd-release octopus` makes sure no old OSDs are joining the cluster
- `ceph mgr module enable pg_autoscaler` Enables the autoscaler. Please verify with @jan--f , if we want it
- `ceph mgr module enable telemetry` + `ceph telemetry on` enables the telemetry module. optional. Please verify with @jan--f , if we should enable this
- `ceph osd set require-min-compat-client luminous` please ask @tserong 
- `ceph balancer mode upmap` and `ceph balancer on` -> We should already have a balancer section in the SES 7 docs. please make sure they match

**Comment by jan--f** [comment]
> ceph mgr module enable pg_autoscaler Enables the autoscaler. Please verify with @jan--f , if we want it

Yeah we do want customers to use the autoscaler. Can we add a link to 
https://susedoc.github.io/doc-ses/master/html/ses-admin/cha-storage-datamgm.html#op-pgs-autoscaler
please. Just enabling the module puts existing pools in warn mode I believe, whereas new pools are in state `on`. I think its worth explicitly calling that out.

> ceph mgr module enable telemetry + ceph telemetry on enables the telemetry module. optional. Please verify with @jan--f , if we should enable this

Yeah we want this as well, though I wonder if we need to add a note regarding the phone home functionality. @l-mb any input on this?

Otherwise the steps look good imho.

**Comment by tserong** [comment]
> `ceph osd set require-min-compat-client luminous` please ask @tserong

This is required in order for the upmap balancer mode to work, and is actually now the default in upstream master since https://github.com/ceph/ceph/commit/986c271b756. There's also a bit more information about this in a blog post I just found: https://blog.nuvotex.de/ceph/ The only kink is that changing this setting prevents pre-luminous clients. Some further random googling indicates the CephFS kernel client might still report itself as Jewel, but I'm not sure if this is true in our case and/or is supported anyway. @jan--f do you have any idea about this latter point?

**Comment by luis-henrix** [comment]
> CephFS kernel client might still report itself as Jewel

That's true, old kernels that still don't support the MSG_ADDR2, FS_BTIME and FS_CHANGE_ATTR features will be reported as 'jewel'.  As for the SLE15-* we should be fine, these features have been backported; the SLE12-* kernels do *not* have them, though.  Also, other distros kernels may or may not have them depending on kernel versions (>= 5.3) and backports.

**Comment by jan--f** [comment]
@tbazant @tserong sounds like we need to add a note that `ceph osd set require-min-compat-client luminous` should only be set if no pre-luminous clients are currently connected (check `ceph versions`) _and_ no such clients are expected to join. For the latter I guess we just mention SLE12 and earlier as pre-luminous clients. Also adding a note that this is needed for the upmap balancer sounds appropriate. Thoughts?

**Comment by tserong** [comment]
Sounds good to me @jan--f
