### ISSUE TITLE
[doc] 7.2  Upgrading the Salt Master - remove " insecure: true" and explain how to add the trusted CA of the registry to /etc/pki/trust/anchors

### ISSUE THREAD

**Issue by Martin-Weiss** [SUSE/doc-ses#867]
### Type of report
   - [ x] bug
   - [ ] feature request

### Source Document
7.2  Upgrading the Salt Master:

https://documentation.suse.com/ses/7/single-html/ses-deployment/#upgrade-salt-master

### Summary
We must not use "insecure: true" - we have to add the CA cert of the signing CA to /etc/pki/trust/anchors and execute "update-ca-certificates".

**Comment by sebastian-philipp** [comment]
lgtm. 

In addition, we no longer support insecure registries at all.

**Comment by tbazant** [comment]
@sebastian-philipp I'll gladly update the docs but would prefer a little more explanation/procedure here, or is one liner enough?

**Comment by sebastian-philipp** [comment]
background is: We've decided to reduce the number of supported deployments, thus we **only support the harbor registry**. as harbor supports https, there is not reason for use to support insecure registries anymore.  afaik we're linking to harbor in a different place. 

that's why we should not recommend users to set `insecure: true`
