### ISSUE TITLE
ceph mds deactivate fs_name:rank is an invalid command.

### ISSUE THREAD

**Issue by bmemmott71** [SUSE/doc-ses#989]
**Link To Section**
[Please provide a link to the section or chapter you are reporting this bug for.](https://documentation.suse.com/ses/6/single-html/ses-deployment/#ceph-cephfs-multimds)

**Summary**
ceph mds deactivate fs_name:rank is an invalid command.

**Notes**
I believe the command can be removed from the doc.

**Comment by tbazant** [comment]
@tserong can you please clarify if and what exactly to remove here?

**Comment by tserong** [comment]
Yeah, we need to remove the `ceph mds deactivate fs_name:rank` command and associated description.

A couple of lines up, it says "In order to shrink the MDS cluster prior to an update, two steps are necessary. First, set max_mds so that only one instance remains:'. This should be changed to "In order to shrink the MDS cluster prior to an update, set max_mds so that only one instance remains", then we can just drop the "deactivate" stuff.

**Comment by bmemmott71** [comment]
Hi Thomas

No. Just remove the following:


and after that, explicitly deactivate the other active MDS daemons:

***@***.*** > ceph mds deactivate fs_name:rank

COPY

where rank is the number of an active MDS daemon of a file system instance, ranging from 0 to max_mds-1.



Thanks
Boyd Memmott
L2 SES & SLES support Engineer
www.suse.com
________________________________
